spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test_mongodb
      username: root
      password: mongodb123
#      多数据源配置
#      uri: mongodb://localhost:27017/test_mongodb
